name: Scheduled Deduplication

on:
  schedule:
    - cron: "*/1 * * * *"  # 每天 UTC 时间的 00:00 执行一次

jobs:
  deduplicate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deduplicate file
      run: |
        cd ..
        sed '$!N; /^\(.*\)\n\1$/!P; D' list.txt