name: Scheduled Deduplication

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  deduplicate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deduplicate file
      run: |
        python remove_repeat.py
